POST {{ws-uri}}/cestzam/service/myminfin/login/complete
Accept: application/json
Content-Type: application/json

{
  "cestzamContext": "{{cestzamContext}}"
}

> {%
 client.global.set("cestzamContext", response.body.cestzamContext);
%}
