version: '3.6'

services:

  cestzam-ws:
    #    image: cestzam-ws
    build: .
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787 -jar /app.jar -s/conf/thorntail.yml
    env_file:
      - ./runtime/config/jaeger.env
      - ./runtime/config/cestzam.env
      - ./runtime/config/cestzam.private.env
    volumes:
      - ./runtime/thorntail/config.yml:/conf/thorntail.yml
      - ./runtime/config/cestzam.tokens.private.json:/config/cestzam-ws/cestzam.health.czam.tokensJson
    ports:
      - '18080:8080'
      - '18787:8787'
    networks:
      - swarm

  cestzam-sync:
    image: openjdk:11
    command: java -jar /myminfinsync.jar
    environment:
      - CESTZAM_TARGET_PATH=/fs
      - CESTZAM_API_URI=cestzam-ws:8080/
      - CESTZAM_AUTH_LOGIN=
      - CESTZAM_AUTH_PASSWORD=
      - 'CESTZAM_AUTH_TOKENS_JSON={"1": "ABCDEFG", ...}'
      # Only process a single mandator, by ssin (national number)
#      - CESTZAM_MANDATOR_SINGLE_SSIN=
      # Only process mandators whom fullname matches pattern
#      - CESTZAM_MANDATOR_NAME_PATTERN=
      # Only process documents for providers matching pattern
#      - CESTZAM_DOCUMENT_PROVIDER_NAME_PATTERN=
      # Only process documents from a specific date
#      - CESTZAM_DOCUMENT_FROM_DATE=
    volumes:
      - ./cestzam-myminfin-filesystem-sync/target/cestzam-myminfin-filesystem-sync-jar-with-dependencies.jar:/myminfinsync.jar
      - ./cestzam-myminfin-filesystem-sync/target/fs:/fs


networks:
  swarm:
    external: true
