POST {{ws-uri}}/cestzam/service/myminfin/mandate/activate
Accept: application/json
Content-Type: application/json

{
   "myminfinContext": {
      "cestzamContext": "{{cestzamContext}}"
   },
   "mandate": {
    // ...
   }
}

> {%
 client.global.set("cestzamContext", response.body.cestzamContext);
%}
