POST {{ws-uri}}/cestzam/service/myminfin/mandate/list
Accept: application/json
Content-Type: application/json

{
   "myminfinContext": {
      "cestzamContext": "{{cestzamContext}}"
   },
   "mandateType": "CITIZEN"
}

