POST {{ws-uri}}/cestzam/service/myminfin/ubo/company/10839531/composition
Accept: application/json
Content-Type: application/json

{
  "myminfinContext": {
    "cestzamContext": "{{cestzamContext}}"
  }
}
